import { useCallback, useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { Modal, ConfirmDialog } from '@/components/ui/modal';
import { Campo, Input, Select, Textarea } from '@/components/ui/form';
import { idPessoa } from '@/lib/identidade';
import { useDominio, noQuadro } from '@/lib/dominio';
import { buscarOrdensPerformance } from '@/lib/performanceOS';
import { validarEntrega, novaPessoa } from '@/lib/performance';
import { formatDate } from '@/lib/format';
import type { CicloPerformance, EntregaPerformance, OrdemPerformance } from '@/data/performance';

export function EntregaModal({competencia,ciclo,pessoaId,registro,onFechar,onSalvar,onRemover}:{competencia:string;ciclo:CicloPerformance;pessoaId:string;registro?:EntregaPerformance;onFechar:()=>void;onSalvar:(e:EntregaPerformance[])=>void;onRemover:(e:EntregaPerformance)=>void}) {
  const d=useDominio();
  const nomePessoa=(id:string)=>`${d.nomeColab(id)} · ID ${idPessoa(d.colabById.get(id)?.cpf)??id}`;
  const [ordens,setOrdens]=useState<OrdemPerformance[]>([]); const [carregando,setCarregando]=useState(false);const [erro,setErro]=useState<string[]>([]);const [consulta,setConsulta]=useState('');const [busca,setBusca]=useState('');const [excluir,setExcluir]=useState(false);
  const [os,setOS]=useState<OrdemPerformance|null>(registro?.os??null);
  const [p,setP]=useState({participacao:registro?.participacao??100,complexidade:registro?.complexidade??1,evidencia:registro?.evidencia??'',aceite:registro?.aceite??false,qualidade:registro?.qualidade??'pendente',prazo:registro?.prazo??'pendente',justificativa:registro?.justificativa??''});
  const [equipe,setEquipe]=useState<{id:string;participacao:number}[]>([{id:pessoaId,participacao:registro?.participacao??100}]);
  const [ajudante,setAjudante]=useState('');
  const osAtual=ordens.find(o=>o.id===os?.id);
  const retratoDiferente=!!registro&&!!osAtual&&JSON.stringify(osAtual)!==JSON.stringify(os);
  const consultar=useCallback(async()=>{setCarregando(true);setErro([]);try{const r=await buscarOrdensPerformance(competencia);setOrdens(r.ordens);setConsulta(r.consultadoEm);}catch(e){setErro([e instanceof Error?e.message:'Não foi possível consultar.']);}finally{setCarregando(false);}},[competencia]);
  useEffect(()=>{void consultar();},[consultar]); // modal é montado para uma única competência
  const salvar=()=>{
    if(!os){setErro(['Selecione uma O.S. concluída.']);return;}
    const novas=equipe.map(x=>({id:registro?.id??crypto.randomUUID(),colaboradorId:x.id,os,...p,participacao:x.participacao}));
    const pessoas=[...ciclo.pessoas,...equipe.filter(x=>!ciclo.pessoas.some(y=>y.colaboradorId===x.id)).map(x=>novaPessoa(x.id))];
    const teste={...ciclo,pessoas,entregas:[...ciclo.entregas.filter(x=>!novas.some(n=>n.id===x.id)),...novas]};
    const erros=novas.flatMap(e=>validarEntrega(e,teste));
    if(ciclo.pessoas.some(x=>equipe.some(y=>y.id===x.colaboradorId)&&x.aprovacao))erros.push('Reabra a aprovação da pessoa antes de alterar entregas.');
    if(erros.length){setErro([...new Set(erros)]);return;}onSalvar(novas);
  };
  return <Modal aberto onFechar={onFechar} titulo={registro?'Conferir entrega e participação':'Vincular O.S. e equipe da entrega'} largura="max-w-4xl" rodape={<>{registro&&<button className="btn-ghost text-red-700" onClick={()=>setExcluir(true)}>Remover vínculo</button>}<button className="btn-ghost" onClick={onFechar}>Cancelar</button><button className="btn-primary" onClick={salvar}>Salvar vínculo{equipe.length>1?'s':''}</button></>}><div className="space-y-4">
    {!!erro.length&&<div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro.map(e=><p key={e}>{e}</p>)}</div>}
    <div className="flex flex-wrap items-end gap-2"><Campo label="Buscar O.S. ou cliente" className="min-w-0 flex-1"><Input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Número, cliente ou serviço"/></Campo><button className="btn-outline" disabled={carregando} onClick={()=>void consultar()}><RefreshCw className="h-4 w-4"/>{carregando?'Consultando…':'Atualizar PCP'}</button></div>
    <Campo label="O.S. concluída no mês"><Select value={os?.id??''} disabled={!!registro} onChange={e=>{const ordem=ordens.find(x=>x.id===e.target.value);setOS(ordem??null);if(ordem){const mesmo=ciclo.entregas.find(x=>x.os.id===ordem.id);setP({...p,complexidade:mesmo?.complexidade??1,qualidade:'pendente',prazo:'pendente',aceite:false});}}}><option value="">Selecione uma entrega de {competencia}</option>{registro&&<option value={registro.os.id}>O.S. {registro.os.numero} · {registro.os.cliente}</option>}{ordens.filter(x=>(!registro||x.id!==registro.os.id)&&(!busca||`${x.numero} ${x.cliente} ${x.servico}`.toLocaleLowerCase('pt-BR').includes(busca.toLocaleLowerCase('pt-BR')))).map(x=><option value={x.id} key={x.id}>O.S. {x.numero} · {x.cliente} · {formatDate(x.finalizadaEm)}</option>)}</Select></Campo>
    {consulta&&<p className="text-xs text-slate-500">Consulta de {new Date(consulta).toLocaleString('pt-BR')}. {ordens.length} O.S. concluída(s) no mês. Os vínculos guardam o retrato conferido da entrega.</p>}
    {registro&&consulta&&!osAtual&&<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Esta O.S. não aparece entre as concluídas deste mês na consulta atual. Confira no PCP antes de manter a participação.</p>}
    {retratoDiferente&&<div className="rounded-xl bg-amber-50 p-3 text-sm"><p>A O.S. tem dados diferentes na consulta atual. Você está vendo o retrato anteriormente conferido.</p><button className="btn-outline mt-2" onClick={()=>{setOS(osAtual!);setP({...p,aceite:false,qualidade:'pendente',prazo:'pendente'});}}>Usar dados atuais e conferir novamente</button></div>}
    {os&&<div className="rounded-xl bg-slate-50 p-4 text-sm"><p className="font-semibold">{os.servico||'Serviço sem descrição'}</p><p>Conclusão: {formatDate(os.finalizadaEm)} · Prazo: {os.prazo?formatDate(os.prazo):'Não informado'}</p><p>Equipe indicada no PCP: {os.equipe.join(', ')||'Não informada'}</p><p>{os.retrabalho?'Há retrabalho marcado no PCP. Confira a causa.':'Sem marcação de retrabalho no PCP; confirme a qualidade.'}</p>{os.baixaAutomatica&&<p className="mt-2 text-amber-800">Conclusão marcada por atualização automática do ERP. Confira a execução e o aceite antes de pontuar.</p>}</div>}
    <fieldset className="space-y-3 rounded-xl border p-4"><legend className="px-1 font-semibold">Quem participou desta entrega</legend><p className="text-sm text-slate-500">A equipe pode mudar a cada O.S. Inclua quem ajudou e reparta a participação. O histórico continua ligado às pessoas desta entrega.</p>{equipe.map(x=><div key={x.id} className="flex flex-wrap items-end gap-3"><p className="min-w-0 flex-1 pb-2 font-medium">{nomePessoa(x.id)}</p><Campo label="Participação (%)" className="w-32"><Input type="number" min="0.01" max="100" step="0.01" value={x.participacao} onChange={e=>setEquipe(equipe.map(y=>y.id===x.id?{...y,participacao:Number(e.target.value)}:y))}/></Campo>{x.id!==pessoaId&&<button className="btn-ghost" onClick={()=>setEquipe(equipe.filter(y=>y.id!==x.id))}>Retirar</button>}</div>)}{!registro&&<div className="flex flex-wrap items-end gap-2"><Campo label="Acrescentar outra pessoa" className="min-w-0 flex-1"><Select value={ajudante} onChange={e=>setAjudante(e.target.value)}><option value="">Selecione quem também participou</option>{d.colaboradores.filter(c=>noQuadro(c)&&!c.ehDirecao&&!equipe.some(x=>x.id===c.id)).sort((a,b)=>a.nome.localeCompare(b.nome)).map(c=><option key={c.id} value={c.id}>{nomePessoa(c.id)}</option>)}</Select></Campo><button className="btn-outline" disabled={!ajudante} onClick={()=>{setEquipe([...equipe,{id:ajudante,participacao:0}]);setAjudante('');}}>Acrescentar</button><button className="btn-ghost" onClick={()=>{const usados=ciclo.entregas.filter(e=>e.os.id===os?.id).reduce((n,e)=>n+e.participacao,0);const disponivel=Math.max(0,100-usados);const parte=Math.floor(disponivel/equipe.length*100)/100;setEquipe(equipe.map((e,i)=>({...e,participacao:i===equipe.length-1?Math.round((disponivel-parte*i)*100)/100:parte})));}}>Dividir saldo igualmente</button></div>}<p className="text-sm font-medium">Participação destes vínculos: {equipe.reduce((n,x)=>n+x.participacao,0).toFixed(2)}%</p></fieldset>
    <Campo label="Complexidade da O.S." hint="Mesma régua para toda a equipe. Documente o motivo na evidência; tamanho, acesso, montagem e tempo padrão ajudam na comparação."><Select value={p.complexidade} onChange={e=>setP({...p,complexidade:Number(e.target.value)})}>{['1 · Simples','2 · Pequena','3 · Intermediária','4 · Complexa','5 · Muito complexa'].map((s,i)=><option key={s} value={i+1}>{s}</option>)}</Select></Campo>
    <div className="grid gap-3 sm:grid-cols-2"><Campo label="Qualidade da entrega"><Select value={p.qualidade} onChange={e=>setP({...p,qualidade:e.target.value as typeof p.qualidade})}><option value="pendente">A conferir</option><option value="sem_retrabalho">Sem retrabalho de execução</option><option value="execucao">Retrabalho atribuído à execução</option><option value="externo">Ocorrência externa à execução</option></Select></Campo><Campo label="Cumprimento do prazo"><Select value={p.prazo} onChange={e=>setP({...p,prazo:e.target.value as typeof p.prazo})}><option value="pendente">A conferir</option><option value="no_prazo">Entregue no prazo combinado</option><option value="atraso">Atraso sob controle da equipe</option><option value="externo">Impedimento externo — fora do indicador</option></Select></Campo></div>
    <Campo label="Evidência da entrega e da complexidade" hint="Aceite, data, responsável pela conferência e referência da foto/checklist no PCP. Não inclua informação médica."><Textarea value={p.evidencia} onChange={e=>setP({...p,evidencia:e.target.value})}/></Campo><Campo label="Causa e justificativa" hint="Necessária para retrabalho, atraso ou impedimento externo."><Textarea value={p.justificativa} onChange={e=>setP({...p,justificativa:e.target.value})}/></Campo><label className="flex items-center gap-2"><input type="checkbox" checked={p.aceite} onChange={e=>setP({...p,aceite:e.target.checked})}/>Conferi a execução e o aceite desta entrega</label>
    {equipe.length>1&&<p className="text-sm text-slate-500">Qualidade e prazo serão aplicados às participações selecionadas. Depois, abra cada vínculo para registrar uma responsabilidade individual diferente, se houver evidência.</p>}
    <ConfirmDialog aberto={excluir} onFechar={()=>setExcluir(false)} titulo="Remover vínculo?" mensagem="A O.S. continua no PCP. Apenas a participação nesta apuração será removida." onConfirmar={()=>{if(registro)onRemover(registro);}}/>
  </div></Modal>;
}
