import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Award, Plus, FileDown, Settings2, ChevronRight } from 'lucide-react';
import { PageHeader } from '@/components/ui/page-header';
import { StatCard } from '@/components/ui/stat-card';
import { Modal } from '@/components/ui/modal';
import { Campo, Input, Select, Textarea } from '@/components/ui/form';
import { useToast } from '@/components/ui/toast';
import { obter, useColecao } from '@/lib/store';
import { idPessoa } from '@/lib/identidade';
import { useDominio, noQuadro } from '@/lib/dominio';
import { useSessao } from '@/lib/session';
import { apurarPessoa, CRITERIOS_COLABORACAO, dinheiro, horas, mesAtual, novaPessoa, novoCiclo, validarAprovacao, validarRegra } from '@/lib/performance';
import { exportarPerformance } from '@/lib/performancePdf';
import { EntregaModal } from '@/components/performance/entrega-modal';
import type { CicloPerformance, EntregaPerformance, PessoaPerformance, RegraPerformance } from '@/data/performance';

const nulo=(n:number|null)=>n===null?'A conferir':`${n.toFixed(1)} / 100`;
export default function Performance() {
  const d=useDominio();
  const nomePessoa=(id:string)=>`${d.nomeColab(id)} · ID ${idPessoa(d.colabById.get(id)?.cpf)??id}`; const sessao=useSessao(); const toast=useToast();
  const store=useColecao('performanceCiclos'); const plantoes=useColecao('plantoes'); const pontos=useColecao('pontos');
  const original=useRef('');
  const [mes,setMes]=useState(mesAtual); const [adicionar,setAdicionar]=useState(false); const [pessoaIdEscolhida,setPessoaIdEscolhida]=useState('');
  const [pessoa,setPessoa]=useState<PessoaPerformance|null>(null);
  const [regra,setRegra]=useState<RegraPerformance|null>(null);
  const [entrega,setEntrega]=useState<{pessoaId:string;registro?:EntregaPerformance}|null>(null);
  const [aprovando,setAprovando]=useState<PessoaPerformance|null>(null); const [valor,setValor]=useState(''); const [justificativa,setJustificativa]=useState('');
  const [reabrindo,setReabrindo]=useState<PessoaPerformance|null>(null);
  const [erro,setErro]=useState<string[]>([]); const [baixando,setBaixando]=useState(false);
  const ciclo=store.items.find(c=>c.competencia===mes)??novoCiclo(mes);
  const atual=()=>obter('performanceCiclos').find(c=>c.competencia===mes)??novoCiclo(mes);
  const retrato=(c:CicloPerformance)=>JSON.stringify([c.competencia,c.regra,c.pessoas,c.entregas,c.historico]);
  const iniciarEdicao=()=>{original.current=retrato(atual());};
  const aprovadas=ciclo.pessoas.filter(p=>p.aprovacao);
  const calculos=ciclo.pessoas.map(p=>({p,a:apurarPessoa(ciclo,p)}));
  const salvar=(c: CicloPerformance,acao: string)=>{
    if(sessao?.perfil!=='ADMIN_RH')return false;
    if(original.current!==retrato(atual())){setErro(['A apuração mudou enquanto você editava. Feche a janela e abra novamente para conferir a versão atual.']);return false;}
    try{store.criarOuAtualizar({...c,historico:[...c.historico,{em:new Date().toISOString(),por:sessao.colaboradorId,acao}].slice(-200)});original.current=retrato(atual());setErro([]);toast('Salvo. Acompanhe a sincronização no topo.','sucesso');return true;}catch(e){setErro([e instanceof Error?e.message:'Não foi possível salvar.']);return false;}
  };
  const abrirPessoa=(p:PessoaPerformance)=>{iniciarEdicao();setErro([]);setPessoa(structuredClone(p));};
  const emEdicao=pessoa?{...ciclo,pessoas:ciclo.pessoas.map(p=>p.colaboradorId===pessoa.colaboradorId?pessoa:p)}:ciclo;
  const analise=pessoa?apurarPessoa(emEdicao,pessoa):null;
  const editada=pessoa&&JSON.stringify(pessoa)!==JSON.stringify(ciclo.pessoas.find(p=>p.colaboradorId===pessoa.colaboradorId));
  const pdf=async()=>{setBaixando(true);try{await exportarPerformance(ciclo,nomePessoa);}catch{toast('Não foi possível gerar o PDF.','erro');}finally{setBaixando(false);}};
  const extrasEscala=(id:string)=>plantoes.items.filter(p=>!p.cancelado&&p.data.startsWith(mes)).flatMap(p=>p.participantes).filter(p=>p.colaboradorId===id&&p.situacao==='Realizado').reduce((a,b)=>a+(b.extrasMin??0),0);
  const extrasPonto=(id:string)=>pontos.items.filter(p=>p.competencia===mes&&p.colaboradorId===id);
  const caixaErros=!!erro.length&&<div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro.map(e=><p key={e}>{e}</p>)}</div>;
  return <div className="space-y-5"><PageHeader title="Performance" description="Entregas comprovadas, qualidade e reconhecimento. Uma apuração clara para quem instala e para quem decide."><button className="btn-outline" disabled={baixando} onClick={()=>void pdf()}><FileDown className="h-4 w-4"/>{baixando?'Gerando…':'Relatório em PDF'}</button></PageHeader>
    <div className="card flex flex-wrap items-end justify-between gap-4 p-4"><div className="flex flex-wrap items-end gap-3"><Campo label="Mês de apuração"><Input type="month" value={mes} onChange={e=>{if(e.target.value){setMes(e.target.value);setErro([]);}}}/></Campo><button className="btn-ghost" onClick={()=>setMes(mesAtual())}>Mês atual</button></div><div className="flex flex-wrap gap-2"><button className="btn-outline" onClick={()=>{iniciarEdicao();setErro([]);setRegra(structuredClone(ciclo.regra));}}><Settings2 className="h-4 w-4"/>Critérios e valores</button><button className="btn-primary" onClick={()=>{iniciarEdicao();setPessoaIdEscolhida('');setErro([]);setAdicionar(true);}}><Plus className="h-4 w-4"/>Incluir pessoa</button></div></div>
    {caixaErros&&!pessoa&&!regra&&!adicionar&&!aprovando&&!reabrindo&&caixaErros}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Pessoas em apuração" value={ciclo.pessoas.length}/><StatCard label="O.S. vinculadas" value={new Set(ciclo.entregas.map(e=>e.os.id)).size} hint="Participação repartida entre a equipe"/><StatCard label="Propostas aprovadas" value={dinheiro(aprovadas.reduce((n,p)=>n+p.aprovacao!.valor,0))} hint={`${aprovadas.length} pessoa(s) · ainda não é pagamento`}/><StatCard label="Orçamento disponível" value={dinheiro(Math.max(0,ciclo.regra.orcamento-aprovadas.reduce((n,p)=>n+p.aprovacao!.valor,0)))} hint="Definido em Critérios e valores"/></div>
    {!ciclo.pessoas.length&&<div className="card p-8"><Award className="mb-4 h-10 w-10 text-brand"/><h2 className="text-xl font-semibold text-brand">Comece pela equipe de instalação</h2><p className="mt-2 max-w-3xl text-slate-500">Inclua as pessoas, combine as metas e vincule as O.S. concluídas. O sistema apresenta a nota com as evidências e uma proposta de bonificação para sua revisão.</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{['1. Combine critérios e orçamento','2. Confira entregas e participação','3. Revise e aprove a proposta'].map(t=><div key={t} className="rounded-xl bg-slate-50 p-4 font-medium">{t}</div>)}</div></div>}
    <div className="space-y-3">{calculos.map(({p,a})=><button className="card flex w-full flex-wrap items-center justify-between gap-4 p-5 text-left transition hover:border-brand/40" key={p.colaboradorId} onClick={()=>abrirPessoa(p)}><div><h2 className="text-lg font-semibold">{nomePessoa(p.colaboradorId)}</h2><p className="mt-1 text-sm text-slate-500">{a.aceitas.length} entrega(s) conferida(s) · {a.pontos.toFixed(2)} pontos · {horas(extrasEscala(p.colaboradorId))} extras na escala</p></div><div className="flex items-center gap-5"><div><p className="font-semibold text-brand">{p.aprovacao?'Proposta aprovada':a.nota===null?'A conferir':`Nota ${a.nota.toFixed(1)}`}</p><p className="text-sm text-slate-500">{p.aprovacao?dinheiro(p.aprovacao.valor):a.elegivel?`${dinheiro(a.sugestao)} sugeridos`:'Abrir apuração'}</p></div><ChevronRight className="h-5 w-5"/></div></button>)}</div>
    <details className="card p-5"><summary className="cursor-pointer font-semibold text-brand">Como funciona a bonificação dos instaladores</summary><div className="mt-4 space-y-3 text-sm leading-relaxed text-slate-600"><p><b>Entrega ({ciclo.regra.pesos.entrega}%):</b> pontos de complexidade × participação na O.S., comparados à meta individual. Uma instalação grande vale mais pontos que uma tarefa simples. A soma das participações da equipe não passa de 100%.</p><p><b>Qualidade ({ciclo.regra.pesos.qualidade}%):</b> participação dos pontos entregues sem retrabalho atribuído à execução. Registre e confira a causa; problema de material, alteração do cliente e projeto não são atribuídos automaticamente ao instalador.</p><p><b>Prazo ({ciclo.regra.pesos.prazo}%):</b> entregas no prazo entre as entregas com prazo sob controle da equipe. Impedimentos externos justificados ficam fora desse denominador.</p><p><b>Colaboração ({ciclo.regra.pesos.colaboracao}%):</b> três comportamentos observáveis, com evidências. A régua é 0 (não atendido), 50 (parcial) e 100 (atendido). Horas extras, atestados e ausências protegidas não elevam nem reduzem a nota.</p><p><b>Proposta:</b> teto individual × nota / 100, com nota e qualidade mínimas, superação da referência habitual e limite de orçamento. Os pesos são uma proposta de gestão ajustável, não percentuais previstos em lei.</p><p>Segurança é requisito de execução. Relatar incidente, risco ou interromper trabalho inseguro não deve reduzir bonificação. Não se usa “zero acidentes relatados” como meta.</p><p>Prêmio, gratificação, horas extras e empreitada têm tratamentos diferentes. Valide a política e a convenção coletiva com o responsável trabalhista/contábil antes de pagar. A tela registra uma proposta, sem lançar valores na folha.</p><p className="flex flex-wrap gap-4"><a className="underline" target="_blank" rel="noreferrer" href="https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm">CLT: arts. 59 e 457</a><a className="underline" target="_blank" rel="noreferrer" href="https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-35-nr-35">MTE: trabalho em altura</a></p></div></details>
    {!!ciclo.historico.length&&<details className="card p-5"><summary className="cursor-pointer font-semibold">Histórico da apuração</summary><div className="mt-3 space-y-2 text-sm">{[...ciclo.historico].reverse().map((h,i)=><p key={`${h.em}-${i}`}>{new Date(h.em).toLocaleString('pt-BR')} · {nomePessoa(h.por)} · {h.acao}</p>)}</div></details>}
    {adicionar&&<Modal aberto onFechar={()=>setAdicionar(false)} titulo="Incluir pessoa na apuração" rodape={<><button className="btn-ghost" onClick={()=>setAdicionar(false)}>Cancelar</button><button className="btn-primary" disabled={!pessoaIdEscolhida} onClick={()=>{if(pessoaIdEscolhida&&!ciclo.pessoas.some(p=>p.colaboradorId===pessoaIdEscolhida)&&salvar({...ciclo,pessoas:[...ciclo.pessoas,novaPessoa(pessoaIdEscolhida)]},`Incluiu ${nomePessoa(pessoaIdEscolhida)}`)){setAdicionar(false);abrirPessoa(novaPessoa(pessoaIdEscolhida));}}}>Incluir</button></>}>{caixaErros}<Campo label="Colaborador"><Select value={pessoaIdEscolhida} onChange={e=>setPessoaIdEscolhida(e.target.value)}><option value="">Selecione uma pessoa</option>{d.colaboradores.filter(c=>noQuadro(c)&&!c.ehDirecao&&!ciclo.pessoas.some(p=>p.colaboradorId===c.id)).sort((a,b)=>a.nome.localeCompare(b.nome)).map(c=><option key={c.id} value={c.id}>{nomePessoa(c.id)}</option>)}</Select></Campo></Modal>}
    {regra&&<Modal aberto onFechar={()=>setRegra(null)} titulo="Critérios e valores do mês" largura="max-w-3xl" rodape={<><button className="btn-ghost" onClick={()=>setRegra(null)}>Fechar</button><button className="btn-primary" disabled={!!aprovadas.length} onClick={()=>{const erros=validarRegra(regra);if(erros.length){setErro(erros);return;}if(salvar({...ciclo,regra},'Atualizou os critérios do mês'))setRegra(null);}}>Salvar critérios</button></>}><div className="space-y-4">{caixaErros}{!!aprovadas.length&&<p className="rounded-xl bg-amber-50 p-3">Há propostas aprovadas. Reabra as aprovações antes de alterar a regra do mês.</p>}<fieldset disabled={!!aprovadas.length} className="space-y-4"><p className="text-sm text-slate-500">Pesos propostos para o piloto de instalação. Combine a régua antes do período e mantenha a referência documentada.</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(Object.keys(regra.pesos) as (keyof RegraPerformance['pesos'])[]).map(k=><Campo key={k} label={`${{entrega:'Entrega',qualidade:'Qualidade',prazo:'Prazo',colaboracao:'Colaboração'}[k]} (%)`}><Input type="number" min="0" max="100" value={regra.pesos[k]} onChange={e=>setRegra({...regra,pesos:{...regra.pesos,[k]:Number(e.target.value)}})}/></Campo>)}</div><div className="grid gap-3 sm:grid-cols-2">{([{k:'notaMinima',nome:'Nota mínima (0–100)'},{k:'qualidadeMinima',nome:'Qualidade mínima (0–100)'},{k:'tetoIndividual',nome:'Teto por pessoa (R$)'},{k:'orcamento',nome:'Orçamento do mês (R$)'}] as const).map(x=><Campo label={x.nome} key={x.k}><Input type="number" min="0" step="0.01" value={regra[x.k]} onChange={e=>setRegra({...regra,[x.k]:Number(e.target.value)})}/></Campo>)}</div><Campo label="Referência habitual e critérios combinados" obrigatorio hint="Registre período de referência, método de complexidade, metas combinadas, data e responsáveis. Não use só o faturamento da O.S."><Textarea value={regra.referencia} onChange={e=>setRegra({...regra,referencia:e.target.value})}/></Campo></fieldset></div></Modal>}
    {pessoa&&analise&&<Modal aberto onFechar={()=>setPessoa(null)} titulo={nomePessoa(pessoa.colaboradorId)} descricao={`Performance · ${mes.slice(5)}/${mes.slice(0,4)}`} largura="max-w-5xl" rodape={<><button className="btn-ghost" onClick={()=>setPessoa(null)}>Fechar</button>{!pessoa.aprovacao&&<button className="btn-primary" onClick={()=>{if(!Number.isFinite(pessoa.habitual)||pessoa.habitual<0||!Number.isFinite(pessoa.meta)||pessoa.meta<0){setErro(['Metas e referência não podem ser negativas.']);return;}if(salvar(emEdicao,`Conferiu ${nomePessoa(pessoa.colaboradorId)}`))setPessoa(null);}}>Salvar avaliação</button>}</>}><div className="space-y-5">{caixaErros}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{(Object.keys(analise.notas) as (keyof typeof analise.notas)[]).map(k=><StatCard key={k} label={{entrega:'Entrega',qualidade:'Qualidade',prazo:'Prazo',colaboracao:'Colaboração'}[k]} value={nulo(analise.notas[k])}/>)}</div>
      <div className="rounded-xl bg-slate-50 p-4 text-sm"><b>Horas extras, em separado:</b> {horas(extrasEscala(pessoa.colaboradorId))} conferidas em plantões. {extrasPonto(pessoa.colaboradorId).length===1?`${horas(extrasPonto(pessoa.colaboradorId)[0].extrasMin)} no ponto do mês.`:extrasPonto(pessoa.colaboradorId).length>1?'Mais de um espelho no mês: conferir os períodos no Ponto.':'Ainda sem espelho de ponto no mês.'} As fontes não são somadas. <Link className="underline" to="/ponto">Conferir ponto</Link></div>
      <fieldset disabled={!!pessoa.aprovacao} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Campo label="Referência habitual (pontos)" hint="Resultado ordinário de um período comparável."><Input type="number" min="0" step="0.1" value={pessoa.habitual} onChange={e=>setPessoa({...pessoa,habitual:Number(e.target.value)})}/></Campo><Campo label="Meta superior (pontos)" hint="Ajuste ao serviço, à participação e à disponibilidade combinada."><Input type="number" min="0" step="0.1" value={pessoa.meta} onChange={e=>setPessoa({...pessoa,meta:Number(e.target.value)})}/></Campo></div>
      <h3 className="font-semibold text-brand">Colaboração observável</h3><div className="grid gap-3 sm:grid-cols-3">{CRITERIOS_COLABORACAO.map((label,i)=><Campo label={label} key={label}><Select value={pessoa.colaboracao[i]??''} onChange={e=>{const notas=[...pessoa.colaboracao] as PessoaPerformance['colaboracao'];notas[i]=e.target.value===''?null:Number(e.target.value);setPessoa({...pessoa,colaboracao:notas});}}><option value="">A conferir</option><option value="0">0 · Não atendido</option><option value="50">50 · Parcial</option><option value="100">100 · Atendido</option></Select></Campo>)}</div><Campo label="Evidências da colaboração" hint="Descreva fatos e datas. Evite rótulos como 'bom' ou 'ruim'."><Textarea value={pessoa.evidenciaColaboracao} onChange={e=>setPessoa({...pessoa,evidenciaColaboracao:e.target.value})}/></Campo><Campo label="Contexto e observações"><Textarea value={pessoa.contexto} onChange={e=>setPessoa({...pessoa,contexto:e.target.value})} placeholder="Mudanças de escopo, disponibilidade combinada, impedimentos e resposta da pessoa."/></Campo></fieldset>
      <section><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold text-brand">Entregas e ordens de serviço</h3>{!pessoa.aprovacao&&<button className="btn-outline" disabled={!!editada} title={editada?'Salve a avaliação antes de vincular O.S.':undefined} onClick={()=>setEntrega({pessoaId:pessoa.colaboradorId})}><Plus className="h-4 w-4"/>Vincular O.S. do PCP</button>}</div>{editada&&<p className="mb-2 text-sm text-amber-700">Salve a avaliação para vincular O.S. ou aprovar a proposta.</p>}{!analise.linhas.length&&<p className="rounded-xl border border-dashed p-5 text-slate-500">Vincule as O.S. concluídas em que a pessoa trabalhou. O nome da equipe no PCP serve como referência; a participação é conferida aqui.</p>}{analise.linhas.map(e=><button key={e.id} disabled={!!pessoa.aprovacao||!!editada} className="mb-2 block w-full rounded-xl border p-4 text-left hover:bg-slate-50" onClick={()=>setEntrega({pessoaId:pessoa.colaboradorId,registro:e})}><b>O.S. {e.os.numero}</b> · {e.os.cliente}<span className="mt-1 block text-sm text-slate-500">{e.participacao}% de participação · complexidade {e.complexidade}/5 · {e.aceite?'Aceite conferido':'Aceite pendente'} · {e.qualidade==='pendente'?'Qualidade a conferir':e.qualidade==='execucao'?'Retrabalho de execução':e.qualidade==='externo'?'Ocorrência externa':'Sem retrabalho'}</span></button>)}</section>
      <div className="rounded-xl border border-brand/20 bg-brand/5 p-5"><h3 className="font-semibold text-brand">Proposta de bonificação</h3><p className="mt-2 text-xl font-semibold">{pessoa.aprovacao?dinheiro(pessoa.aprovacao.valor):dinheiro(analise.sugestao)}</p><p className="mt-1 text-sm">{analise.nota===null?'A apuração ainda tem pendências.':`Nota ${analise.nota.toFixed(1)} × teto ${dinheiro(ciclo.regra.tetoIndividual)} / 100.`} {analise.nota!==null&&!analise.elegivel?'Ainda não atende aos critérios mínimos ou à superação da referência habitual.':''}</p>{!!analise.pendencias.length&&<ul className="mt-3 list-inside list-disc text-sm text-amber-800">{analise.pendencias.map(e=><li key={e}>{e}</li>)}</ul>}<p className="mt-3 text-sm text-slate-500">A aprovação registra sua decisão e preserva a regra aplicada. O pagamento é tratado posteriormente na folha.</p>{pessoa.aprovacao?<div className="mt-3"><p className="text-sm">Aprovada por {nomePessoa(pessoa.aprovacao.por)} · {new Date(pessoa.aprovacao.em).toLocaleString('pt-BR')}</p><button className="btn-outline mt-3" onClick={()=>{setJustificativa('');setReabrindo(pessoa);}}>Reabrir para correção</button></div>:<button className="btn-primary mt-4" disabled={!analise.elegivel||!!editada} onClick={()=>{setValor(String(analise.sugestao));setJustificativa('');setErro([]);setAprovando(pessoa);}}>Revisar e aprovar proposta</button>}</div>
    </div></Modal>}
    {entrega&&<EntregaModal competencia={mes} ciclo={ciclo} pessoaId={entrega.pessoaId} registro={entrega.registro} onFechar={()=>setEntrega(null)} onSalvar={novas=>{const ids=[...new Set(novas.map(e=>e.colaboradorId))];const pessoas=[...ciclo.pessoas,...ids.filter(id=>!ciclo.pessoas.some(p=>p.colaboradorId===id)).map(novaPessoa)];if(salvar({...ciclo,pessoas,entregas:[...ciclo.entregas.filter(x=>!novas.some(e=>e.id===x.id)),...novas]},`Conferiu equipe e participação na O.S. ${novas[0].os.numero}`))setEntrega(null);}} onRemover={e=>{if(salvar({...ciclo,entregas:ciclo.entregas.filter(x=>x.id!==e.id)},`Removeu vínculo da O.S. ${e.os.numero} de ${nomePessoa(e.colaboradorId)}`))setEntrega(null);}}/>}
    {aprovando&&<Modal aberto onFechar={()=>setAprovando(null)} titulo="Aprovar proposta de bonificação" rodape={<><button className="btn-ghost" onClick={()=>setAprovando(null)}>Cancelar</button><button className="btn-primary" onClick={()=>{const erros=validarAprovacao(ciclo,aprovando,Number(valor),justificativa);if(erros.length){setErro(erros);return;}const a=apurarPessoa(ciclo,aprovando);const p={...aprovando,aprovacao:{valor:Number(valor),nota:a.nota!,em:new Date().toISOString(),por:sessao!.colaboradorId,justificativa,regra:structuredClone(ciclo.regra)}};if(salvar({...ciclo,pessoas:ciclo.pessoas.map(x=>x.colaboradorId===p.colaboradorId?p:x)},`Aprovou proposta de ${nomePessoa(p.colaboradorId)}`)){setAprovando(null);setPessoa(p);}}}>Aprovar proposta</button></>}><div className="space-y-4">{caixaErros}<p>{nomePessoa(aprovando.colaboradorId)} · {mes}</p><Campo label="Valor aprovado (R$)"><Input type="number" min="0" step="0.01" value={valor} onChange={e=>setValor(e.target.value)}/></Campo><Campo label="Justificativa da decisão"><Textarea value={justificativa} onChange={e=>setJustificativa(e.target.value)}/></Campo><p className="text-sm text-slate-500">Confirme as evidências e a política acordada. Esta ação não paga nem lança verba na folha.</p></div></Modal>}
    {reabrindo&&<Modal aberto onFechar={()=>setReabrindo(null)} titulo="Reabrir apuração" rodape={<><button className="btn-ghost" onClick={()=>setReabrindo(null)}>Cancelar</button><button className="btn-primary" disabled={!justificativa.trim()} onClick={()=>{const {aprovacao,...p}=reabrindo;if(salvar({...ciclo,pessoas:ciclo.pessoas.map(x=>x.colaboradorId===p.colaboradorId?p:x)},`Reabriu ${nomePessoa(p.colaboradorId)}; proposta anterior ${dinheiro(aprovacao!.valor)}; motivo: ${justificativa}`)){setReabrindo(null);setPessoa(p);}}}>Reabrir</button></>}><Campo label="Motivo da correção"><Textarea value={justificativa} onChange={e=>setJustificativa(e.target.value)}/></Campo></Modal>}
  </div>;
}
